"""
Mock data generators for Grimperium tests.

This module provides functions to generate mock data that mimics
the structure and characteristics of real Chemperium data.

Use these generators when fixtures in conftest.py are not sufficient
or when you need customized mock data.

Example:
    >>> from tests.fixtures.mock_data import generate_chemperium_mock
    >>> df = generate_chemperium_mock(n_molecules=100)
    >>> print(df.columns)

"""

import numpy as np
import pandas as pd


def generate_chemperium_mock(
    n_molecules: int = 100,
    include_cp: bool = True,
    n_cp_columns: int = 45,
    random_state: int = 42,
) -> pd.DataFrame:
    """
    Generate mock Chemperium-like DataFrame.

    Args:
        n_molecules: Number of molecules to generate
        include_cp: Whether to include heat capacity columns
        n_cp_columns: Number of Cp columns (1-45)
        random_state: Random seed for reproducibility

    Returns:
        DataFrame with mock thermodynamic data

    Example:
        >>> df = generate_chemperium_mock(n_molecules=1000)
        >>> print(f"Shape: {df.shape}")

    """
    np.random.seed(random_state)

    # Generate molecular properties
    nheavy = np.random.randint(1, 20, n_molecules)
    charge = np.random.choice([0, 0, 0, 0, 1, -1], n_molecules)
    multiplicity = np.random.choice([1, 1, 1, 2, 3], n_molecules)

    # Generate thermodynamic properties
    # H298 roughly correlates with nheavy
    h298_base = -10 * nheavy + np.random.normal(0, 10, n_molecules)
    h298_cbs = h298_base + np.random.normal(0, 1, n_molecules)
    h298_b3 = h298_cbs + np.random.normal(0, 2, n_molecules)

    # S298 increases with nheavy
    s298 = 30 + 5 * nheavy + np.random.normal(0, 3, n_molecules)

    # Generate mock SMILES (simplified, not chemically valid)
    smiles = [f"C{i}H{2*i+2}" for i in range(1, n_molecules + 1)]

    df = pd.DataFrame(
        {
            "smiles": smiles,
            "charge": charge,
            "multiplicity": multiplicity,
            "nheavy": nheavy,
            "H298_cbs": h298_cbs,
            "H298_b3": h298_b3,
            "S298": s298,
        }
    )

    # Add heat capacity columns
    if include_cp:
        cp_base = 5 + 2 * nheavy
        for i in range(1, n_cp_columns + 1):
            # Cp increases with temperature (simplified model)
            df[f"cp_{i}"] = cp_base + 0.1 * i + np.random.normal(0, 0.5, n_molecules)

    return df


def generate_pm7_mock(
    smiles: list[str],
    h298_cbs: np.ndarray,
    error_mean: float = 3.0,
    error_std: float = 1.5,
    random_state: int = 42,
) -> pd.DataFrame:
    """
    Generate mock PM7 calculation results.

    PM7 values are generated by adding systematic error to CBS values,
    mimicking real semiempirical method behavior.

    Args:
        smiles: List of SMILES strings
        h298_cbs: CBS enthalpy values (reference)
        error_mean: Mean systematic error in kcal/mol
        error_std: Standard deviation of error
        random_state: Random seed

    Returns:
        DataFrame with smiles and H298_pm7

    Example:
        >>> pm7_df = generate_pm7_mock(smiles_list, h298_cbs_values)
        >>> delta = h298_cbs_values - pm7_df["H298_pm7"].values

    """
    np.random.seed(random_state)
    n = len(smiles)

    # PM7 typically underestimates binding
    errors = np.random.normal(error_mean, error_std, n)
    h298_pm7 = h298_cbs + errors  # CBS - error = PM7 → PM7 = CBS + error

    return pd.DataFrame(
        {
            "smiles": smiles,
            "H298_pm7": h298_pm7,
        }
    )


def generate_features_mock(
    n_samples: int,
    n_tabular: int = 3,
    n_morgan_bits: int = 256,
    n_rdkit_desc: int = 10,
    random_state: int = 42,
) -> np.ndarray:
    """
    Generate mock feature matrix.

    Args:
        n_samples: Number of samples
        n_tabular: Number of tabular features
        n_morgan_bits: Number of Morgan fingerprint bits
        n_rdkit_desc: Number of RDKit descriptors
        random_state: Random seed

    Returns:
        Feature matrix of shape (n_samples, n_features)

    """
    np.random.seed(random_state)

    # Tabular features (nheavy, charge, multiplicity - continuous for simplicity)
    tabular = np.random.randn(n_samples, n_tabular)
    tabular[:, 0] = np.abs(tabular[:, 0]) * 5 + 1  # nheavy: positive int-like

    # Morgan fingerprints (binary)
    morgan = np.random.randint(0, 2, (n_samples, n_morgan_bits))

    # RDKit descriptors (continuous)
    rdkit = np.random.randn(n_samples, n_rdkit_desc)

    return np.hstack([tabular, morgan, rdkit])


def generate_training_data(
    n_samples: int = 1000,
    test_size: float = 0.2,
    random_state: int = 42,
) -> dict:
    """
    Generate complete training dataset.

    Args:
        n_samples: Total number of samples
        test_size: Fraction for test set
        random_state: Random seed

    Returns:
        Dictionary with:
            - X_train, X_test: Feature matrices
            - y_train, y_test: Delta targets
            - h298_pm7_train, h298_pm7_test: PM7 values
            - h298_cbs_train, h298_cbs_test: CBS values (ground truth)

    Example:
        >>> data = generate_training_data(n_samples=1000)
        >>> X_train = data["X_train"]
        >>> y_train = data["y_train"]

    """
    np.random.seed(random_state)

    # Generate base data
    df = generate_chemperium_mock(
        n_samples, include_cp=False, random_state=random_state
    )
    pm7_df = generate_pm7_mock(
        df["smiles"].tolist(),
        df["H298_cbs"].values,
        random_state=random_state,
    )

    # Merge and compute deltas
    merged = df.merge(pm7_df, on="smiles")
    merged["delta_pm7"] = merged["H298_cbs"] - merged["H298_pm7"]

    # Generate features
    X = generate_features_mock(n_samples, random_state=random_state)
    y = merged["delta_pm7"].values

    # Split
    n_test = int(n_samples * test_size)
    n_train = n_samples - n_test

    indices = np.random.permutation(n_samples)
    train_idx = indices[:n_train]
    test_idx = indices[n_train:]

    return {
        "X_train": X[train_idx],
        "X_test": X[test_idx],
        "y_train": y[train_idx],
        "y_test": y[test_idx],
        "h298_pm7_train": merged["H298_pm7"].values[train_idx],
        "h298_pm7_test": merged["H298_pm7"].values[test_idx],
        "h298_cbs_train": merged["H298_cbs"].values[train_idx],
        "h298_cbs_test": merged["H298_cbs"].values[test_idx],
        "smiles_train": [merged["smiles"].iloc[i] for i in train_idx],
        "smiles_test": [merged["smiles"].iloc[i] for i in test_idx],
    }


def make_small_chemperium_df(
    n: int = 100,
    random_state: int = 42,
) -> pd.DataFrame:
    """
    Create a small Chemperium DataFrame for testing.

    This is a convenience wrapper around generate_chemperium_mock()
    with sensible defaults for unit tests. Includes all optional columns
    (H298_b3, S298, cp_1...cp_45).

    Args:
        n: Number of molecules to generate
        random_state: Random seed for reproducibility

    Returns:
        DataFrame with full Chemperium schema

    Example:
        >>> df = make_small_chemperium_df(n=50)
        >>> assert "H298_cbs" in df.columns
        >>> assert "cp_45" in df.columns

    """
    return generate_chemperium_mock(
        n_molecules=n,
        include_cp=True,
        n_cp_columns=45,
        random_state=random_state,
    )


def make_chemperium_with_pm7_df(
    n: int = 100,
    random_state: int = 42,
    pm7_error_mean: float = 3.0,
    pm7_error_std: float = 1.5,
) -> pd.DataFrame:
    """
    Create a Chemperium DataFrame with PM7 enthalpy column.

    Useful for testing delta computation and merge operations.
    The H298_pm7 column simulates PM7 systematic error (~3±1.5 kcal/mol
    relative to CBS reference).

    Args:
        n: Number of molecules to generate
        random_state: Random seed for reproducibility
        pm7_error_mean: Mean PM7 error in kcal/mol
        pm7_error_std: Standard deviation of PM7 error

    Returns:
        DataFrame with Chemperium columns plus H298_pm7

    Example:
        >>> df = make_chemperium_with_pm7_df(n=50)
        >>> delta = df["H298_cbs"] - df["H298_pm7"]
        >>> assert abs(delta.mean()) < 10  # Realistic error range

    """
    # Generate base Chemperium data
    df = generate_chemperium_mock(
        n_molecules=n,
        include_cp=True,
        n_cp_columns=45,
        random_state=random_state,
    )

    # Generate PM7 values with systematic error
    np.random.seed(random_state + 1)  # Different seed for PM7 noise
    errors = np.random.normal(pm7_error_mean, pm7_error_std, n)
    df["H298_pm7"] = df["H298_cbs"] + errors

    return df
