"""
Molecule data model for batch processing.

This module defines the Molecule dataclass hierarchy used by the batch
processing system. It provides a type-safe representation of molecules
with their properties, results, and metadata.

The hierarchy:
- Molecule (main class)
  - identity: MoleculeIdentity (mol_id, smiles)
  - properties: MoleculeProperties (nheavy, charge, multiplicity, H298_cbs)
  - results: MoleculeResults (crest/mopac outputs, deltas)
  - meta: MoleculeMeta (status, reruns, timestamps)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

# Re-export MoleculeStatus from existing module for consistency
from grimperium.crest_pm7.batch.enums import MoleculeStatus

__all__ = [
    "Molecule",
    "MoleculeIdentity",
    "MoleculeProperties",
    "MoleculeResults",
    "MoleculeMeta",
    "MoleculeStatus",
]


@dataclass
class MoleculeIdentity:
    """Core identification fields for a molecule.

    These fields uniquely identify a molecule and are immutable
    after creation.
    """

    mol_id: str
    """Unique molecule identifier."""

    smiles: str
    """SMILES string representation."""

    batch_id: str | None = None
    """Batch this molecule belongs to."""


@dataclass
class MoleculeProperties:
    """Physical and chemical properties of a molecule.

    These are input properties (from the CBS dataset) used for
    delta-learning calculations.
    """

    nheavy: int
    """Number of heavy atoms (non-hydrogen)."""

    charge: int = 0
    """Molecular charge."""

    multiplicity: int = 1
    """Spin multiplicity (1=singlet, 2=doublet, 3=triplet)."""

    H298_cbs: float | None = None
    """CBS-QB3 reference enthalpy at 298K (kcal/mol)."""

    nrotbonds: int = 0
    """Number of rotatable bonds."""


@dataclass
class MoleculeResults:
    """Results from CREST and MOPAC calculations.

    Populated after processing by CalculationExecutor.
    """

    # CREST results
    crest_status: str | None = None
    """CREST execution status."""

    crest_conformers_generated: int | None = None
    """Number of conformers generated by CREST."""

    crest_time: float | None = None
    """CREST execution time in seconds."""

    # MOPAC results
    mopac_status: str | None = None
    """MOPAC execution status."""

    mopac_time: float | None = None
    """MOPAC execution time in seconds."""

    # Delta values (PM7 - CBS differences)
    delta_1: float | None = None
    """Delta for best conformer (kcal/mol)."""

    delta_2: float | None = None
    """Delta for second conformer (kcal/mol)."""

    delta_3: float | None = None
    """Delta for third conformer (kcal/mol)."""

    most_stable_hof: float | None = None
    """Most stable heat of formation from PM7 (kcal/mol)."""

    # Error tracking
    error_message: str | None = None
    """Error message if processing failed."""


@dataclass
class MoleculeMeta:
    """Metadata for batch processing state.

    Tracks processing status, timing, and retry attempts.
    """

    status: MoleculeStatus = MoleculeStatus.PENDING
    """Current processing status."""

    reruns: int = 0
    """Number of rerun attempts."""

    timestamp_added: datetime | None = None
    """When molecule was added to batch."""

    timestamp_started: datetime | None = None
    """When processing started."""

    timestamp_completed: datetime | None = None
    """When processing completed (success or failure)."""


@dataclass
class Molecule:
    """Complete molecule representation for batch processing.

    Combines identity, properties, results, and metadata into
    a single type-safe structure.

    Usage:
        >>> mol = Molecule(
        ...     identity=MoleculeIdentity(mol_id="mol_001", smiles="CCO"),
        ...     properties=MoleculeProperties(nheavy=3),
        ... )
        >>> mol.is_pending
        True
        >>> mol.mol_id
        'mol_001'
    """

    identity: MoleculeIdentity
    """Core identification."""

    properties: MoleculeProperties
    """Physical/chemical properties."""

    results: MoleculeResults = field(default_factory=MoleculeResults)
    """Calculation results."""

    meta: MoleculeMeta = field(default_factory=MoleculeMeta)
    """Processing metadata."""

    # === Convenience Properties ===

    @property
    def mol_id(self) -> str:
        """Shortcut to identity.mol_id."""
        return self.identity.mol_id

    @property
    def smiles(self) -> str:
        """Shortcut to identity.smiles."""
        return self.identity.smiles

    @property
    def status(self) -> MoleculeStatus:
        """Shortcut to meta.status."""
        return self.meta.status

    @property
    def reruns(self) -> int:
        """Shortcut to meta.reruns."""
        return self.meta.reruns

    # === Status Check Properties ===

    @property
    def is_pending(self) -> bool:
        """Check if molecule is pending processing."""
        return self.meta.status == MoleculeStatus.PENDING

    @property
    def is_running(self) -> bool:
        """Check if molecule is currently running."""
        return self.meta.status == MoleculeStatus.RUNNING

    @property
    def is_complete(self) -> bool:
        """Check if molecule completed successfully."""
        return self.meta.status == MoleculeStatus.OK

    @property
    def is_failed(self) -> bool:
        """Check if molecule failed (eligible for rerun)."""
        return self.meta.status == MoleculeStatus.RERUN

    @property
    def is_skipped(self) -> bool:
        """Check if molecule was skipped (max retries exceeded)."""
        return self.meta.status == MoleculeStatus.SKIP

    def can_rerun(self, max_reruns: int) -> bool:
        """Check if molecule is eligible for rerun.

        Args:
            max_reruns: Maximum number of allowed reruns.

        Returns:
            True if failed and reruns < max_reruns.
        """
        return self.is_failed and self.meta.reruns < max_reruns

    # === Factory Methods ===

    @classmethod
    def from_csv_dict(cls, row: dict[str, Any]) -> Molecule:
        """Create Molecule from CSV row dictionary.

        Args:
            row: Dictionary with CSV column values.

        Returns:
            Molecule instance.

        Raises:
            KeyError: If required fields are missing.
            ValueError: If field values are invalid.
        """
        from grimperium.core.value_converter import MoleculeValueConverter

        # Required fields
        mol_id, err = MoleculeValueConverter.to_string(
            row.get("mol_id"), "mol_id", allow_empty=False
        )
        if err or mol_id is None:
            raise ValueError(f"mol_id is required but got: {row.get('mol_id')}")

        smiles, err = MoleculeValueConverter.to_string(
            row.get("smiles"), "smiles", allow_empty=False
        )
        if err or smiles is None:
            raise ValueError(f"smiles is required but got: {row.get('smiles')}")

        nheavy, err = MoleculeValueConverter.to_int(row.get("nheavy"), "nheavy")
        if err or nheavy is None:
            raise ValueError(f"nheavy is required but got: {row.get('nheavy')}")

        # Optional identity fields
        batch_id, _ = MoleculeValueConverter.to_string(
            row.get("batch_id"), "batch_id", allow_empty=True
        )

        # Properties
        charge, _ = MoleculeValueConverter.to_int(row.get("charge", 0), "charge")
        multiplicity, _ = MoleculeValueConverter.to_int(
            row.get("multiplicity", 1), "multiplicity"
        )
        H298_cbs, _ = MoleculeValueConverter.to_float(row.get("H298_cbs"), "H298_cbs")
        nrotbonds, _ = MoleculeValueConverter.to_int(
            row.get("nrotbonds", 0), "nrotbonds"
        )

        # Meta
        status_val, _ = MoleculeValueConverter.to_enum(
            row.get("status", "Pending"), MoleculeStatus, "status"
        )
        status = status_val or MoleculeStatus.PENDING

        reruns, _ = MoleculeValueConverter.to_int(row.get("reruns", 0), "reruns")
        reruns = reruns or 0

        timestamp_added, _ = MoleculeValueConverter.to_datetime(
            row.get("timestamp_added"), "timestamp_added"
        )
        timestamp_started, _ = MoleculeValueConverter.to_datetime(
            row.get("timestamp_started"), "timestamp_started"
        )
        timestamp_completed, _ = MoleculeValueConverter.to_datetime(
            row.get("timestamp_completed"), "timestamp_completed"
        )

        # Results (all optional)
        crest_status, _ = MoleculeValueConverter.to_string(
            row.get("crest_status"), "crest_status", allow_empty=True
        )
        crest_conformers, _ = MoleculeValueConverter.to_int(
            row.get("crest_conformers_generated"), "crest_conformers_generated"
        )
        crest_time, _ = MoleculeValueConverter.to_float(
            row.get("crest_time"), "crest_time"
        )

        mopac_status, _ = MoleculeValueConverter.to_string(
            row.get("mopac_status"), "mopac_status", allow_empty=True
        )
        mopac_time, _ = MoleculeValueConverter.to_float(
            row.get("mopac_time"), "mopac_time"
        )

        delta_1, _ = MoleculeValueConverter.to_float(row.get("delta_1"), "delta_1")
        delta_2, _ = MoleculeValueConverter.to_float(row.get("delta_2"), "delta_2")
        delta_3, _ = MoleculeValueConverter.to_float(row.get("delta_3"), "delta_3")
        most_stable_hof, _ = MoleculeValueConverter.to_float(
            row.get("most_stable_hof"), "most_stable_hof"
        )

        error_message, _ = MoleculeValueConverter.to_string(
            row.get("error_message"), "error_message", allow_empty=True
        )

        return cls(
            identity=MoleculeIdentity(
                mol_id=mol_id,
                smiles=smiles,
                batch_id=batch_id if batch_id else None,
            ),
            properties=MoleculeProperties(
                nheavy=nheavy,
                charge=charge or 0,
                multiplicity=multiplicity or 1,
                H298_cbs=H298_cbs,
                nrotbonds=nrotbonds or 0,
            ),
            results=MoleculeResults(
                crest_status=crest_status if crest_status else None,
                crest_conformers_generated=crest_conformers,
                crest_time=crest_time,
                mopac_status=mopac_status if mopac_status else None,
                mopac_time=mopac_time,
                delta_1=delta_1,
                delta_2=delta_2,
                delta_3=delta_3,
                most_stable_hof=most_stable_hof,
                error_message=error_message if error_message else None,
            ),
            meta=MoleculeMeta(
                status=status,
                reruns=reruns,
                timestamp_added=timestamp_added,
                timestamp_started=timestamp_started,
                timestamp_completed=timestamp_completed,
            ),
        )

    def to_csv_dict(self) -> dict[str, Any]:
        """Convert Molecule to CSV row dictionary.

        Returns:
            Dictionary suitable for CSV export.
        """
        return {
            # Identity
            "mol_id": self.identity.mol_id,
            "smiles": self.identity.smiles,
            "batch_id": self.identity.batch_id or "",
            # Properties
            "nheavy": self.properties.nheavy,
            "charge": self.properties.charge,
            "multiplicity": self.properties.multiplicity,
            "H298_cbs": (
                self.properties.H298_cbs if self.properties.H298_cbs is not None else ""
            ),
            "nrotbonds": self.properties.nrotbonds,
            # Meta
            "status": self.meta.status.value,
            "reruns": self.meta.reruns,
            "timestamp_added": (
                self.meta.timestamp_added.isoformat()
                if self.meta.timestamp_added
                else ""
            ),
            "timestamp_started": (
                self.meta.timestamp_started.isoformat()
                if self.meta.timestamp_started
                else ""
            ),
            "timestamp_completed": (
                self.meta.timestamp_completed.isoformat()
                if self.meta.timestamp_completed
                else ""
            ),
            # Results
            "crest_status": self.results.crest_status or "",  # strings OK with `or`
            "crest_conformers_generated": (
                self.results.crest_conformers_generated
                if self.results.crest_conformers_generated is not None
                else ""
            ),
            "crest_time": (
                self.results.crest_time if self.results.crest_time is not None else ""
            ),
            "mopac_status": self.results.mopac_status or "",  # strings OK with `or`
            "mopac_time": (
                self.results.mopac_time if self.results.mopac_time is not None else ""
            ),
            "delta_1": self.results.delta_1 if self.results.delta_1 is not None else "",
            "delta_2": self.results.delta_2 if self.results.delta_2 is not None else "",
            "delta_3": self.results.delta_3 if self.results.delta_3 is not None else "",
            "most_stable_hof": (
                self.results.most_stable_hof
                if self.results.most_stable_hof is not None
                else ""
            ),
            "error_message": self.results.error_message or "",  # strings OK with `or`
        }
