"""
Orchestration layer for single-molecule prediction in the Calculate view.

Thin compatibility wrapper over the canonical :class:`PM7DeltaLearningRunner`.
The scientific logic (CREST/PM7 → features → delta inference) lives only in the
runner; this module derives the legacy :class:`CalcPipelineResult` view model
from the canonical result so existing CLI callers keep working.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from grimperium.calculation.contracts.enums import PropertyRole
from grimperium.calculation.contracts.models import (
    MoleculeCalculationResult,
    PropertyEstimate,
)
from grimperium.calculation.runners.pm7_delta_runner import (
    PM7DeltaLearningRunner,
    PM7DeltaRunnerError,
)
from grimperium.cli.calculation_features import build_pm7_delta_feature_frame
from grimperium.cli.model_compatibility import ModelCompatibilityError
from grimperium.crest_pm7.config import PM7Config
from grimperium.crest_pm7.molecule_processor import PM7Result
from grimperium.crest_pm7.pipeline import CRESTPM7Pipeline
from grimperium.ml.persistence import load_model, load_model_metadata


class CalcPipelineError(Exception):
    """Raised when pipeline processing fails."""

    pass


@dataclass
class CalcPipelineResult:
    """Result from single-molecule pipeline execution."""

    h298_pm7: float  # Raw MOPAC HOF, kcal/mol
    delta_correction: float  # Model-predicted delta, kcal/mol
    h298_corrected: float  # h298_pm7 + delta_correction
    n_conformers: int  # Conformers generated by CREST
    execution_time: float  # Total seconds
    model_version: str  # From metadata
    # Canonical domain result backing the view-model values above (single source
    # of truth). Optional so hand-built instances in tests remain valid.
    canonical: MoleculeCalculationResult | None = field(default=None)


def _estimate(
    result: MoleculeCalculationResult, role: PropertyRole
) -> PropertyEstimate:
    for estimate in result.estimates:
        if estimate.role is role:
            return estimate
    raise CalcPipelineError(f"Canonical result is missing a {role.value} estimate")


def run_single_molecule_prediction(
    smiles: str,
    mol_id: str,
    model_path: Path,
    config: PM7Config,
    progress_callback: Callable[[str], None] | None = None,
    *,
    canonical_run_id: str | None = None,
) -> CalcPipelineResult:
    """Run the canonical PM7 + Delta Learning runner and adapt its result.

    Args:
        smiles: SMILES string.
        mol_id: Molecule identifier.
        model_path: Path to the trained model bundle.
        config: PM7Config for the pipeline.
        progress_callback: Optional progress callback.

    Returns:
        CalcPipelineResult with the canonical result attached.

    Raises:
        CalcPipelineError: If CREST, MOPAC, feature assembly, or inference fails.
    """
    captured: dict[str, PM7Result] = {}

    def _process(molecule_id: str, mol_smiles: str) -> PM7Result:
        # References the module-level CRESTPM7Pipeline so callers/tests can patch
        # it at the calc_pipeline seam.
        result = CRESTPM7Pipeline(config).process_molecule(molecule_id, mol_smiles)
        captured["pm7"] = result
        return result

    runner = PM7DeltaLearningRunner(
        config=config,
        pm7_processor=_process,
        model_loader=load_model,
        metadata_loader=load_model_metadata,
        feature_builder=build_pm7_delta_feature_frame,
        # The legacy entry point historically did not validate the model; that is
        # the caller's responsibility (the CalcView pre-validates).
        model_validator=lambda _path, _method: None,
    )

    try:
        canonical = runner.calculate_single_smiles(
            smiles,
            molecule_id=mol_id,
            model_path=model_path,
            progress_callback=progress_callback,
            run_id=canonical_run_id,
        )
    except (PM7DeltaRunnerError, ModelCompatibilityError) as exc:
        raise CalcPipelineError(str(exc)) from exc

    pm7_result = captured["pm7"]
    metadata = load_model_metadata(model_path)

    return CalcPipelineResult(
        h298_pm7=_estimate(canonical, PropertyRole.BASELINE).value_kcal_mol or 0.0,
        delta_correction=_estimate(canonical, PropertyRole.CORRECTION).value_kcal_mol
        or 0.0,
        h298_corrected=_estimate(canonical, PropertyRole.FINAL).value_kcal_mol or 0.0,
        n_conformers=pm7_result.crest_conformers_generated,
        execution_time=(pm7_result.total_execution_time or 0.0)
        + (pm7_result.crest_time or 0.0),
        model_version=str(metadata.get("version", "unknown")),
        canonical=canonical,
    )
