"""
Orchestration layer for single-molecule prediction in the Calculate view.

Handles the complete pipeline: SMILES → geometry → CREST → MOPAC → delta correction.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from grimperium.cli.calculation_features import build_pm7_delta_feature_frame
from grimperium.crest_pm7.config import PM7Config
from grimperium.crest_pm7.pipeline import CRESTPM7Pipeline
from grimperium.ml.persistence import load_model, load_model_metadata


class CalcPipelineError(Exception):
    """Raised when pipeline processing fails."""

    pass


@dataclass
class CalcPipelineResult:
    """Result from single-molecule pipeline execution."""

    h298_pm7: float  # Raw MOPAC HOF, kcal/mol
    delta_correction: float  # Model-predicted delta, kcal/mol
    h298_corrected: float  # h298_pm7 + delta_correction
    n_conformers: int  # Conformers generated by CREST
    execution_time: float  # Total seconds
    model_version: str  # From metadata


def run_single_molecule_prediction(
    smiles: str,
    mol_id: str,
    model_path: Path,
    config: PM7Config,
    progress_callback: Callable[[str], None] | None = None,
) -> CalcPipelineResult:
    """
    Run the complete pipeline for a single molecule.

    Orchestrates:
    1. CREST-PM7 processing (geometry, conformer search, MOPAC)
    2. Feature extraction (RDKit, CREST, MOPAC)
    3. Model loading and prediction
    4. Delta correction extraction from the predicted H298

    Args:
        smiles: SMILES string
        mol_id: Molecule identifier
        model_path: Path to trained model file
        config: PM7Config for pipeline
        progress_callback: Optional callback for progress updates

    Returns:
        CalcPipelineResult with h298_pm7, delta_correction, h298_corrected

    Raises:
        CalcPipelineError: If CREST, MOPAC, or model loading fails
    """
    # Step 1: Run CREST-PM7 pipeline
    if progress_callback:
        progress_callback("⏳ Generating geometry and conformers...")

    pipeline = CRESTPM7Pipeline(config)
    pm7_result = pipeline.process_molecule(mol_id, smiles)

    # Check for processing errors
    if not pm7_result.success:
        error_msg = pm7_result.error_message or "Unknown error"
        raise CalcPipelineError(f"Pipeline failed: {error_msg}")

    # Step 2: Extract H298 (PM7 heat of formation)
    h298_pm7 = pm7_result.most_stable_hof
    if h298_pm7 is None:
        raise CalcPipelineError("No stable conformer found - cannot extract HOF")

    # Step 3: Load model and feature pipeline
    if progress_callback:
        progress_callback("⚡ Loading model...")

    try:
        learner, feature_pipeline = load_model(model_path)
        metadata = load_model_metadata(model_path)
        model_version = metadata.get("version", "unknown")
    except Exception as e:
        raise CalcPipelineError(f"Failed to load model: {e}") from e

    # Step 4: Assemble features for prediction
    if progress_callback:
        progress_callback("🔧 Extracting molecular features...")

    try:
        df = build_pm7_delta_feature_frame(smiles, pm7_result)

        # Transform features
        X = feature_pipeline.transform(df)

    except Exception as e:
        raise CalcPipelineError(f"Feature extraction failed: {e}") from e

    # Step 5: Make prediction
    if progress_callback:
        progress_callback("🧠 Computing delta correction...")

    try:
        import numpy as np

        # DeltaLearner.predict returns the final H298 prediction, not the pure delta.
        y_pm7_array = np.array([h298_pm7])
        h298_cbs_pred = float(learner.predict(X, y_pm7_array)[0])
        delta_correction = h298_cbs_pred - h298_pm7
    except Exception as e:
        raise CalcPipelineError(f"Prediction failed: {e}") from e

    # Step 6: Compute corrected H298
    h298_corrected = h298_cbs_pred

    # Compute total execution time
    total_time = (pm7_result.total_execution_time or 0.0) + (
        pm7_result.crest_time or 0.0
    )

    return CalcPipelineResult(
        h298_pm7=h298_pm7,
        delta_correction=delta_correction,
        h298_corrected=h298_corrected,
        n_conformers=pm7_result.crest_conformers_generated,
        execution_time=total_time,
        model_version=model_version,
    )
