"""
Orchestration layer for single-molecule prediction in the Calculate view.

Handles the complete pipeline: SMILES → geometry → CREST → MOPAC → delta correction.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from grimperium.core.descriptors import extract_all_rdkit_descriptors
from grimperium.crest_pm7.config import PM7Config
from grimperium.crest_pm7.mopac_descriptors import extract_mopac_descriptors
from grimperium.crest_pm7.pipeline import CRESTPM7Pipeline
from grimperium.ml.persistence import load_model, load_model_metadata


class CalcPipelineError(Exception):
    """Raised when pipeline processing fails."""

    pass


@dataclass
class CalcPipelineResult:
    """Result from single-molecule pipeline execution."""

    h298_pm7: float  # Raw MOPAC HOF, kcal/mol
    delta_correction: float  # Model-predicted delta, kcal/mol
    h298_corrected: float  # h298_pm7 + delta_correction
    n_conformers: int  # Conformers generated by CREST
    execution_time: float  # Total seconds
    model_version: str  # From metadata


def run_single_molecule_prediction(
    smiles: str,
    mol_id: str,
    model_path: Path,
    config: PM7Config,
    progress_callback: Callable[[str], None] | None = None,
) -> CalcPipelineResult:
    """
    Run the complete pipeline for a single molecule.

    Orchestrates:
    1. CREST-PM7 processing (geometry, conformer search, MOPAC)
    2. Feature extraction (RDKit, CREST, MOPAC)
    3. Model loading and prediction
    4. Delta correction computation

    Args:
        smiles: SMILES string
        mol_id: Molecule identifier
        model_path: Path to trained model file
        config: PM7Config for pipeline
        progress_callback: Optional callback for progress updates

    Returns:
        CalcPipelineResult with h298_pm7, delta_correction, h298_corrected

    Raises:
        CalcPipelineError: If CREST, MOPAC, or model loading fails
    """
    # Step 1: Run CREST-PM7 pipeline
    if progress_callback:
        progress_callback("⏳ Generating geometry and conformers...")

    pipeline = CRESTPM7Pipeline(config)
    pm7_result = pipeline.process_molecule(mol_id, smiles)

    # Check for processing errors
    if not pm7_result.success:
        error_msg = pm7_result.error_message or "Unknown error"
        raise CalcPipelineError(f"Pipeline failed: {error_msg}")

    # Step 2: Extract H298 (PM7 heat of formation)
    h298_pm7 = pm7_result.most_stable_hof
    if h298_pm7 is None:
        raise CalcPipelineError("No stable conformer found - cannot extract HOF")

    # Step 3: Load model and feature pipeline
    if progress_callback:
        progress_callback("⚡ Loading model...")

    try:
        learner, feature_pipeline = load_model(model_path)
        metadata = load_model_metadata(model_path)
        model_version = metadata.get("version", "unknown")
    except Exception as e:
        raise CalcPipelineError(f"Failed to load model: {e}") from e

    # Step 4: Assemble features for prediction
    if progress_callback:
        progress_callback("🔧 Extracting molecular features...")

    try:
        # RDKit descriptors (15 features)
        rdkit_descs = extract_all_rdkit_descriptors(smiles)

        # Structural features from PM7Result
        nheavy = pm7_result.nheavy or 0
        multiplicity = 1  # Default
        charge = 0  # Default

        # CREST stats
        crest_conformers_generated = pm7_result.crest_conformers_generated
        num_conformers_selected = pm7_result.num_conformers_selected or 0
        crest_time_s = pm7_result.crest_time or 0.0

        # MOPAC electronic descriptors (9 features)
        # From the most stable conformer's output
        selected_conformer = pm7_result.get_selected_conformer()
        if selected_conformer is None or selected_conformer.mopac_output_file is None:
            raise CalcPipelineError("No successful MOPAC output found")

        mopac_descs = extract_mopac_descriptors(selected_conformer.mopac_output_file)

        # Build feature dictionary (must match FeaturePipeline expectations)
        features_dict: dict[str, float | int] = {
            # Structural
            "nheavy": nheavy,
            "multiplicity": multiplicity,
            "charge": charge,
            # RDKit (15)
            **rdkit_descs,
            # CREST
            "crest_conformers_generated": crest_conformers_generated,
            "num_conformers_selected": num_conformers_selected,
            "crest_time_s": crest_time_s,
            # MOPAC electronic (9)
            **mopac_descs,
            # Baseline
            "H298_pm7": h298_pm7,
        }

        # Build DataFrame (1 row, 30 columns)
        df = pd.DataFrame([features_dict])

        # Transform features
        X = feature_pipeline.transform(df)

    except Exception as e:
        raise CalcPipelineError(f"Feature extraction failed: {e}") from e

    # Step 5: Make prediction
    if progress_callback:
        progress_callback("🧠 Computing delta correction...")

    try:
        import numpy as np

        # DeltaLearner.predict requires both X and y_pm7
        y_pm7_array = np.array([[h298_pm7]])
        delta_correction = float(learner.predict(X, y_pm7_array)[0])
    except Exception as e:
        raise CalcPipelineError(f"Prediction failed: {e}") from e

    # Step 6: Compute corrected H298
    h298_corrected = h298_pm7 + delta_correction

    # Compute total execution time
    total_time = (pm7_result.total_execution_time or 0.0) + (
        pm7_result.crest_time or 0.0
    )

    return CalcPipelineResult(
        h298_pm7=h298_pm7,
        delta_correction=delta_correction,
        h298_corrected=h298_corrected,
        n_conformers=crest_conformers_generated,
        execution_time=total_time,
        model_version=model_version,
    )
